apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinitum-server
  namespace: infinitum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infinitum-server
  template:
    metadata:
      labels:
        app: infinitum-server
    spec:
      containers:
      - name: infinitum-server
        image: bitcoinnanolabs/infinitum-server
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 3Gi
        ports:
        - containerPort: 5076
          name: api
        command: ["/bin/bash", "-c"]
        args: ["python infinitumcast.py --host 0.0.0.0 --log-to-stdout --websocket-url ws://10.98.0.6:7078"]
        env:
          - name: REDIS_HOST
            value: redis-0.redis
          - name: REDIS_DB
            value: "10"
          - name: WORK_URL
            value: http://pippin-nano.pippin:11338
          - name: DEBUG
            value: "0"
          - name: RPC_URL
            value: http://10.98.0.6:7076
          - name: FCM_API_KEY
            valueFrom:
              secretKeyRef:
                name: infinitum
                key: fcm_api_key
          - name: FCM_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: infinitum
                key: fcm_sender
